services:
  pmm-server:
    image: percona/pmm-server:${PMM_TAG}
    container_name: ${PMM_CONTAINER_NAME}
    restart: always
    ports:
      - "${PMM_PORT}:443"
    environment:
      - PMM_WATCHTOWER_HOST=http://watchtower:${WATCHTOWER_PORT}
      - PMM_WATCHTOWER_TOKEN=${WATCHTOWER_TOKEN}
    volumes:
      - pmm-data:/srv
    networks:
      - pmm-net

  watchtower:
    image: containrrr/watchtower
    container_name: ${WATCHTOWER_CONTAINER_NAME}
    restart: always
    ports:
      - "${WATCHTOWER_PORT}:${WATCHTOWER_PORT}"
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN}
    command: >
      --http-api-update
      --http-api-token=${WATCHTOWER_TOKEN}
      --http-api-metrics
      --interval=30
      --cleanup
      --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pmm-net

networks:
  pmm-net:
    driver: bridge
